name:
on:
   push:
      branches:
         - 'main'
jobs:
   build-push:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Login Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
         - name: Build and Push to Docker Hub
           uses: docker/build-push-action@v5
           id: docker_build_client
           with:
              context: .
              file: ./Dockerfile
              builder: ${{steps.buildx.outputs.name}}
              push: true
              tags: dialoguebot/chatbot:latest
